package pam.pamhc2crops.datagen.common.tags;

import static pam.pamhc2crops.init.ItemRegistry.*;

public class ModCropsTag extends ModTags {
    public ModCropsTag() {
        super("crops");
        createTagWithItem(agaveitem.get());
        createTagWithItem(amaranthitem.get());
        createTagWithItem(arrowrootitem.get());
        createTagWithItem(artichokeitem.get());
        createTagWithItem(asparagusitem.get());
        createTagWithItem(barleyitem.get());
        createTagWithItem(beanitem.get());
        createTagWithItem(bellpepperitem.get());
        createTagWithItem(blackberryitem.get());
        createTagWithItem(blueberryitem.get());
        createTagWithItem(broccoliitem.get());
        createTagWithItem(brusselsproutitem.get());
        createTagWithItem(cabbageitem.get());
        createTagWithItem(cactusfruititem.get());
        createTagWithItem(candleberryitem.get());
        createTagWithItem(cantaloupeitem.get());
        createTagWithItem(cassavaitem.get());
        createTagWithItem(caulifloweritem.get());
        createTagWithItem(celeryitem.get());
        createTagWithItem(chickpeaitem.get());
        createTagWithItem(chilipepperitem.get());
        createTagWithItem(coffeebeanitem.get());
        createTagWithItem(cornitem.get());
        createTagWithItem(cottonitem.get());
        createTagWithItem(cranberryitem.get());
        createTagWithItem(cucumberitem.get());
        createTagWithItem(eggplantitem.get());
        createTagWithItem(elderberryitem.get());
        createTagWithItem(flaxitem.get());
        createTagWithItem(garlicitem.get());
        createTagWithItem(gingeritem.get());
        createTagWithItem(grapeitem.get());
        createTagWithItem(greengrapeitem.get());
        createTagWithItem(huckleberryitem.get());
        createTagWithItem(jicamaitem.get());
        createTagWithItem(juniperberryitem.get());
        createTagWithItem(juteitem.get());
        createTagWithItem(kaleitem.get());
        createTagWithItem(kenafitem.get());
        createTagWithItem(kiwiitem.get());
        createTagWithItem(kohlrabiitem.get());
        createTagWithItem(leekitem.get());
        createTagWithItem(lentilitem.get());
        createTagWithItem(lettuceitem.get());
        createTagWithItem(milletitem.get());
        createTagWithItem(mulberryitem.get());
        createTagWithItem(mustardseedsitem.get());
        createTagWithItem(oatsitem.get());
        createTagWithItem("oat", oatsitem.get());
        createTagWithItem(okraitem.get());
        createTagWithItem(onionitem.get());
        createTagWithItem(parsnipitem.get());
        createTagWithItem(peanutitem.get());
        createTagWithItem(peasitem.get());
        createTagWithItem("pea", peasitem.get());
        createTagWithItem(pineappleitem.get());
        createTagWithItem(quinoaitem.get());
        createTagWithItem(radishitem.get());
        createTagWithItem(raspberryitem.get());
        createTagWithItem(rhubarbitem.get());
        createTagWithItem(riceitem.get());
        createTagWithItem(rutabagaitem.get());
        createTagWithItem(ryeitem.get());
        createTagWithItem(scallionitem.get());
        createTagWithItem(sesameseedsitem.get());
        createTagWithItem(sisalitem.get());
        createTagWithItem(soybeanitem.get());
        createTagWithItem(spiceleafitem.get());
        createTagWithItem(spinachitem.get());
        createTagWithItem(strawberryitem.get());
        createTagWithItem(sweetpotatoitem.get());
        createTagWithItem("sweet_potato", sweetpotatoitem.get());
        createTagWithItem(taroitem.get());
        createTagWithItem(tealeafitem.get());
        createTagWithItem(tomatilloitem.get());
        createTagWithItem(tomatoitem.get());
        createTagWithItem(turnipitem.get());
        createTagWithItem(waterchestnutitem.get());
        createTagWithItem(whitemushroomitem.get());
        createTagWithItem(wintersquashitem.get());
        createTagWithItem(zucchiniitem.get());
    }
}
