package pam.pamhc2crops.datagen.common.tags;

import static pam.pamhc2crops.init.ItemRegistry.*;

public class ModSeedsTag extends ModTags {
    public ModSeedsTag() {
        super("seeds");
        createTagSeedWithItem(agaveseeditem.get());
        createTagSeedWithItem(amaranthseeditem.get());
        createTagSeedWithItem(arrowrootseeditem.get());
        createTagSeedWithItem(artichokeseeditem.get());
        createTagSeedWithItem(asparagusseeditem.get());
        createTagSeedWithItem(barleyseeditem.get());
        createTagSeedWithItem(beanseeditem.get());
        createTagSeedWithItem(bellpepperseeditem.get());
        createTagSeedWithItem(blackberryseeditem.get());
        createTagSeedWithItem(blueberryseeditem.get());
        createTagSeedWithItem(broccoliseeditem.get());
        createTagSeedWithItem(brusselsproutseeditem.get());
        createTagSeedWithItem(cabbageseeditem.get());
        createTagSeedWithItem(cactusfruitseeditem.get());
        createTagSeedWithItem(candleberryseeditem.get());
        createTagSeedWithItem(cantaloupeseeditem.get());
        createTagSeedWithItem(cassavaseeditem.get());
        createTagSeedWithItem(cauliflowerseeditem.get());
        createTagSeedWithItem(celeryseeditem.get());
        createTagSeedWithItem(chickpeaseeditem.get());
        createTagSeedWithItem(chilipepperseeditem.get());
        createTagSeedWithItem(coffeebeanseeditem.get());
        createTagSeedWithItem(cornseeditem.get());
        createTagSeedWithItem(cottonseeditem.get());
        createTagSeedWithItem(cranberryseeditem.get());
        createTagSeedWithItem(cucumberseeditem.get());
        createTagSeedWithItem(eggplantseeditem.get());
        createTagSeedWithItem(elderberryseeditem.get());
        createTagSeedWithItem(flaxseeditem.get());
        createTagSeedWithItem(garlicseeditem.get());
        createTagSeedWithItem(gingerseeditem.get());
        createTagSeedWithItem(grapeseeditem.get());
        createTagSeedWithItem(greengrapeseeditem.get());
        createTagSeedWithItem(huckleberryseeditem.get());
        createTagSeedWithItem(jicamaseeditem.get());
        createTagSeedWithItem(juniperberryseeditem.get());
        createTagSeedWithItem(juteseeditem.get());
        createTagSeedWithItem(kaleseeditem.get());
        createTagSeedWithItem(kenafseeditem.get());
        createTagSeedWithItem(kiwiseeditem.get());
        createTagSeedWithItem(kohlrabiseeditem.get());
        createTagSeedWithItem(leekseeditem.get());
        createTagSeedWithItem(lentilseeditem.get());
        createTagSeedWithItem(lettuceseeditem.get());
        createTagSeedWithItem(milletseeditem.get());
        createTagSeedWithItem(mulberryseeditem.get());
        createTagWithItem("mustardseeds", mustardseedsseeditem.get());
        createTagSeedWithItem(oatsseeditem.get());
        createTagSeedWithItem(okraseeditem.get());
        createTagSeedWithItem(onionseeditem.get());
        createTagSeedWithItem(parsnipseeditem.get());
        createTagSeedWithItem(peanutseeditem.get());
        createTagSeedWithItem(peasseeditem.get());
        createTagSeedWithItem(pineappleseeditem.get());
        createTagSeedWithItem(quinoaseeditem.get());
        createTagSeedWithItem(radishseeditem.get());
        createTagSeedWithItem(raspberryseeditem.get());
        createTagSeedWithItem(rhubarbseeditem.get());
        createTagSeedWithItem(riceseeditem.get());
        createTagSeedWithItem(rutabagaseeditem.get());
        createTagSeedWithItem(ryeseeditem.get());
        createTagSeedWithItem(scallionseeditem.get());
        createTagWithItem("sesameseeds", sesameseedsseeditem.get());
        createTagSeedWithItem(sisalseeditem.get());
        createTagSeedWithItem(soybeanseeditem.get());
        createTagSeedWithItem(spiceleafseeditem.get());
        createTagSeedWithItem(spinachseeditem.get());
        createTagSeedWithItem(strawberryseeditem.get());
        createTagSeedWithItem(sweetpotatoseeditem.get());
        createTagSeedWithItem(taroseeditem.get());
        createTagSeedWithItem(tealeafseeditem.get());
        createTagSeedWithItem(tomatilloseeditem.get());
        createTagSeedWithItem(tomatoseeditem.get());
        createTagSeedWithItem(turnipseeditem.get());
        createTagSeedWithItem(waterchestnutseeditem.get());
        createTagSeedWithItem(whitemushroomseeditem.get());
        createTagSeedWithItem(wintersquashseeditem.get());
        createTagSeedWithItem(zucchiniseeditem.get());
    }
}
