package pam.pamhc2crops.datagen.client;

import net.minecraft.data.DataGenerator;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.data.LanguageProvider;
import pam.pamhc2crops.Pamhc2crops;
import pam.pamhc2crops.init.BlockRegistry;

import static pam.pamhc2crops.init.BlockRegistry.*;
import static pam.pamhc2crops.init.ItemRegistry.*;

public class ModLanguageProvfider extends LanguageProvider {
    public ModLanguageProvfider(DataGenerator gen, String locale) {
        super(gen, Pamhc2crops.MOD_ID, locale);
    }

    @Override
    protected void addTranslations() {
        add("itemGroup.pamhc2crops", "Pam's HarvestCraft 2 - Crops");

        // Blocks
        add(pamagavecrop.get(),"Agave Crop");
        add(pamamaranthcrop.get(), "Amaranth Crop");
        add(pamarrowrootcrop.get(), "Arrowroot Crop");
        add(pamartichokecrop.get(), "Artichoke Crop");
        add(pamasparaguscrop.get(),"Asparagus Crop" );
        add(pambarleycrop.get(),"Barley Crop" );
        add(pambeancrop.get(), "Bean Crop");
        add(pambellpeppercrop.get(), "Bellpepper Crop");
        add(pamblackberrycrop.get(),"Blackberry Crop");
        add(pamblueberrycrop.get(), "Blueberry Crop");
        add(pambroccolicrop.get(),"Broccoli Crop");
        add(pambrusselsproutcrop.get(), "Brusselsprout Crop");
        add(pamcabbagecrop.get(), "Cabbage Crop");
        add(pamcactusfruitcrop.get(), "Cactusfruit Crop");
        add(pamcandleberrycrop.get(), "Candleberry Crop");
        add(pamcantaloupecrop.get(), "Cantaloupe Crop");
        add(pamcassavacrop.get(), "Cassava Crop");
        add(pamcauliflowercrop.get(), "Cauliflower Crop");
        add(pamcelerycrop.get(), "Celery Crop");
        add(pamchickpeacrop.get(), "Chickpea Crop");
        add(pamchilipeppercrop.get(), "Chilipepper Crop");
        add(pamcoffeebeancrop.get(), "Coffeebean Crop");
        add(pamcorncrop.get(), "Corn Crop");
        add(pamcottoncrop.get(), "Cotton Crop");
        add(pamcranberrycrop.get(), "Cranberry Crop");
        add(pamcucumbercrop.get(), "Cucumber Crop");
        add(pameggplantcrop.get(), "Eggplant Crop");
        add(pamelderberrycrop.get(), "Elderberry Crop");
        add(pamflaxcrop.get(), "Flax Crop");
        add(pamgarliccrop.get(), "Garlic Crop");
        add(pamgingercrop.get(), "Ginger Crop");
        add(pamgrapecrop.get(), "Grape Crop");
        add(pamgreengrapecrop.get(), "Greengrape Crop");
        add(pamhuckleberrycrop.get(), "Huckleberry Crop");
        add(pamjicamacrop.get(), "Jicama Crop");
        add(pamjuniperberrycrop.get(), "Juniperberry Crop");
        add(pamjutecrop.get(), "Jute Crop");
        add(pamkalecrop.get(), "Kale Crop");
        add(pamkenafcrop.get(), "Kenaf Crop");
        add(pamkiwicrop.get(), "Kiwi Crop");
        add(pamkohlrabicrop.get(), "Kohlrabi Crop");
        add(pamleekcrop.get(), "Leek Crop");
        add(pamlentilcrop.get(), "Lentil Crop");
        add(pamlettucecrop.get(), "Lettuce Crop");
        add(pammilletcrop.get(), "Millet Crop");
        add(pammulberrycrop.get(), "Mulberry Crop");
        add(pammustardseedscrop.get(), "Mustard Seeds Crop");
        add(pamoatscrop.get(), "Oats Crop");
        add(pamokracrop.get(), "Okra Crop");
        add(pamonioncrop.get(), "Onion Crop");
        add(pamparsnipcrop.get(), "Parsnip Crop");
        add(pampeanutcrop.get(), "Peanut Crop");
        add(pampeascrop.get(), "Peas Crop");
        add(pampineapplecrop.get(), "Pineapple Crop");
        add(pamquinoacrop.get(), "Quinoa Crop");
        add(pamradishcrop.get(), "Radish Crop");
        add(pamraspberrycrop.get(), "Raspberry Crop");
        add(pamrhubarbcrop.get(), "Rhubarb Crop");
        add(pamricecrop.get(), "Rice Crop");
        add(pamrutabagacrop.get(), "Rutabaga Crop");
        add(pamryecrop.get(), "Rye Crop");
        add(pamscallioncrop.get(), "Scallion Crop");
        add(pamsesameseedscrop.get(), "Sesame Seeds Crop");
        add(pamsisalcrop.get(), "Sisal Crop");
        add(pamsoybeancrop.get(), "Soybean Crop");
        add(pamspiceleafcrop.get(), "Spiceleaf Crop");
        add(pamspinachcrop.get(), "Spinach Crop");
        add(pamstrawberrycrop.get(), "Strawberry Crop");
        add(pamsweetpotatocrop.get(), "Sweet Potato Crop");
        add(pamtarocrop.get(), "Taro Crop");
        add(pamtealeafcrop.get(), "Tealeaf Crop");
        add(pamtomatillocrop.get(), "Tomatillo Crop");
        add(pamtomatocrop.get(), "Tomato Crop");
        add(pamturnipcrop.get(), "Turnip Crop");
        add(pamwaterchestnutcrop.get(), "Waterchestnut Crop");
        add(pamwhitemushroomcrop.get(), "White Mushroom Crop");
        add(pamwintersquashcrop.get(), "Winter Squash Crop");
        add(pamzucchinicrop.get(), "Zucchini Crop");

        // Gardens
        add(BlockRegistry.aridgarden.get(), "Arid Garden");
        add(BlockRegistry.frostgarden.get(), "Frost Garden");
        add(BlockRegistry.tropicalgarden.get(),  "Shaded Garden");
        add(BlockRegistry.windygarden.get(), "Soggy Garden");
        add(BlockRegistry.shadedgarden.get(), "Tropical Garden");
        add(BlockRegistry.soggygarden.get(), "Windy Garden");

        // Items
        add(agaveitem.get(), "Agave");
        add(amaranthitem.get(), "Amaranth");
        add(arrowrootitem.get(), "Arrowroot");
        add(artichokeitem.get(), "Artichoke");
        add(asparagusitem.get(), "Asparagus");
        add(barleyitem.get(), "Barley");
        add(beanitem.get(), "Bean");
        add(bellpepperitem.get(), "Bellpepper");
        add(blackberryitem.get(), "Blackberry");
        add(blueberryitem.get(), "Blueberry");
        add(broccoliitem.get(), "Broccoli");
        add(brusselsproutitem.get(), "Brusselsprout");
        add(cabbageitem.get(), "Cabbage");
        add(cactusfruititem.get(), "Cactusfruit");
        add(candleberryitem.get(), "Candleberry");
        add(cantaloupeitem.get(), "Cantaloupe");
        add(cassavaitem.get(), "Cassava");
        add(caulifloweritem.get(), "Cauliflower");
        add(celeryitem.get(), "Celery");
        add(chickpeaitem.get(), "Chickpea");
        add(chilipepperitem.get(), "Chilipepper");
        add(coffeebeanitem.get(), "Coffeebean");
        add(cornitem.get(), "Corn");
        add(cottonitem.get(), "Cotton");
        add(cranberryitem.get(), "Cranberry");
        add(cucumberitem.get(), "Cucumber");
        add(eggplantitem.get(), "Eggplant");
        add(elderberryitem.get(), "Elderberry");
        add(flaxitem.get(), "Flax");
        add(garlicitem.get(), "Garlic");
        add(gingeritem.get(), "Ginger");
        add(grapeitem.get(), "Grape");
        add(greengrapeitem.get(), "Green Grape");
        add(huckleberryitem.get(), "Huckleberry");
        add(jicamaitem.get(), "Jicama");
        add(juniperberryitem.get(), "Juniperberry");
        add(juteitem.get(), "Jute");
        add(kaleitem.get(), "Kale");
        add(kenafitem.get(), "Kenaf");
        add(kiwiitem.get(), "Kiwi");
        add(kohlrabiitem.get(), "Kohlrabi");
        add(leekitem.get(), "Leek");
        add(lentilitem.get(), "Lentil");
        add(lettuceitem.get(), "Lettuce");
        add(milletitem.get(), "Millet");
        add(mulberryitem.get(), "Mulberry");
        add(mustardseedsitem.get(), "Mustard Seeds");
        add(oatsitem.get(), "Oats");
        add(okraitem.get(), "Okra");
        add(onionitem.get(), "Onion");
        add(parsnipitem.get(), "Parsnip");
        add(peanutitem.get(), "Peanut");
        add(peasitem.get(), "Peas");
        add(pineappleitem.get(), "Pineapple");
        add(quinoaitem.get(), "Quinoa");
        add(radishitem.get(), "Radish");
        add(raspberryitem.get(), "Raspberry");
        add(rhubarbitem.get(), "Rhubarb");
        add(riceitem.get(), "Rice");
        add(rutabagaitem.get(), "Rutabaga");
        add(ryeitem.get(), "Rye");
        add(scallionitem.get(), "Scallion");
        add(sesameseedsitem.get(), "Sesame Seeds");
        add(sisalitem.get(), "Sisal");
        add(soybeanitem.get(), "Soybean");
        add(spiceleafitem.get(), "Spiceleaf");
        add(spinachitem.get(), "Spinach");
        add(strawberryitem.get(), "Strawberry");
        add(sweetpotatoitem.get(), "Sweet Potato");
        add(taroitem.get(), "Taro");
        add(tealeafitem.get(), "Tealeaf");
        add(tomatilloitem.get(), "Tomatillo");
        add(tomatoitem.get(), "Tomato");
        add(turnipitem.get(), "Turnip");
        add(waterchestnutitem.get(), "Waterchestnut");
        add(whitemushroomitem.get(), "White Mushroom");
        add(wintersquashitem.get(), "Winter Squash");
        add(zucchiniitem.get(), "Zucchini");

        add(agaveseeditem.get(), "Agave Seed");
        add(amaranthseeditem.get(), "Amaranth Seed");
        add(arrowrootseeditem.get(), "Arrowroot Seed");
        add(artichokeseeditem.get(), "Artichoke Seed");
        add(asparagusseeditem.get(), "Asparagus Seed");
        add(barleyseeditem.get(), "Barley Seed");
        add(beanseeditem.get(), "Bean Seed");
        add(bellpepperseeditem.get(), "Bellpepper Seed");
        add(blackberryseeditem.get(), "Blackberry Seed");
        add(blueberryseeditem.get(), "Blueberry Seed");
        add(broccoliseeditem.get(), "Broccoli Seed");
        add(brusselsproutseeditem.get(), "Brusselsprout Seed");
        add(cabbageseeditem.get(), "Cabbage Seed");
        add(cactusfruitseeditem.get(), "Cactusfruit Seed");
        add(candleberryseeditem.get(), "Candleberry Seed");
        add(cantaloupeseeditem.get(), "Cantaloupe Seed");
        add(cassavaseeditem.get(), "Cassava Seed");
        add(cauliflowerseeditem.get(), "Cauliflower Seed");
        add(celeryseeditem.get(), "Celery Seed");
        add(chickpeaseeditem.get(), "Chickpea Seed");
        add(chilipepperseeditem.get(), "Chilipepper Seed");
        add(coffeebeanseeditem.get(), "Coffeebean Seed");
        add(cornseeditem.get(), "Corn Seed");
        add(cottonseeditem.get(), "Cotton Seed");
        add(cranberryseeditem.get(), "Cranberry Seed");
        add(cucumberseeditem.get(), "Cucumber Seed");
        add(eggplantseeditem.get(), "Eggplant Seed");
        add(elderberryseeditem.get(), "Elderberry Seed");
        add(flaxseeditem.get(), "Flax Seed");
        add(garlicseeditem.get(), "Garlic Seed");
        add(gingerseeditem.get(), "Ginger Seed");
        add(grapeseeditem.get(), "Grape Seed");
        add(greengrapeseeditem.get(), "Green Grape Seed");
        add(huckleberryseeditem.get(), "Huckleberry Seed");
        add(jicamaseeditem.get(), "Jicama Seed");
        add(juniperberryseeditem.get(), "Juniperberry Seed");
        add(juteseeditem.get(), "Jute Seed");
        add(kaleseeditem.get(), "Kale Seed");
        add(kenafseeditem.get(), "Kenaf Seed");
        add(kiwiseeditem.get(), "Kiwi Seed");
        add(kohlrabiseeditem.get(), "Kohlrabi Seed");
        add(leekseeditem.get(), "Leek Seed");
        add(lentilseeditem.get(), "Lentil Seed");
        add(lettuceseeditem.get(), "Lettuce Seed");
        add(milletseeditem.get(), "Millet Seed");
        add(mulberryseeditem.get(), "Mulberry Seed");
        add(mustardseedsseeditem.get(), "Mustard Seeds Seed");
        add(oatsseeditem.get(), "Oats Seed");
        add(okraseeditem.get(), "Okra Seed");
        add(onionseeditem.get(), "Onion Seed");
        add(parsnipseeditem.get(), "Parsnip Seed");
        add(peanutseeditem.get(), "Peanut Seed");
        add(peasseeditem.get(), "Peas Seed");
        add(pineappleseeditem.get(), "Pineapple Seed");
        add(quinoaseeditem.get(), "Quinoa Seed");
        add(radishseeditem.get(), "Radish Seed");
        add(raspberryseeditem.get(), "Raspberry Seed");
        add(rhubarbseeditem.get(), "Rhubarb Seed");
        add(riceseeditem.get(), "Rice Seed");
        add(rutabagaseeditem.get(), "Rutabaga Seed");
        add(ryeseeditem.get(), "Rye Seed");
        add(scallionseeditem.get(), "Scallion Seed");
        add(sesameseedsseeditem.get(), "Sesame Seeds Seed");
        add(sisalseeditem.get(), "Sisal Seed");
        add(soybeanseeditem.get(), "Soybean Seed");
        add(spiceleafseeditem.get(), "Spiceleaf Seed");
        add(spinachseeditem.get(), "Spinach Seed");
        add(strawberryseeditem.get(), "Strawberry Seed");
        add(sweetpotatoseeditem.get(), "Sweet Potato Seed");
        add(taroseeditem.get(), "Taro Seed");
        add(tealeafseeditem.get(), "Tealeaf Seed");
        add(tomatilloseeditem.get(), "Tomatillo Seed");
        add(tomatoseeditem.get(), "Tomato Seed");
        add(turnipseeditem.get(), "Turnip Seed");
        add(waterchestnutseeditem.get(), "Waterchestnut Seed");
        add(whitemushroomseeditem.get(), "White Mushroom Seed");
        add(wintersquashseeditem.get(), "Winter Squash Seed");
        add(zucchiniseeditem.get(), "Zucchini Seed");

        add(bakedarrowrootitem.get(), "Baked Arrowroot");
        add(bakedcassavaitem.get(), "Baked Cassava");
        add(roastedgarlicitem.get(), "Roasted Garlic");
        add(bakedjicamaitem.get(), "Baked Jicama");
        add(roastedleekitem.get(), "Roasted Leek");
        add(roastedkohlrabiitem.get(), "Roasted Kohlrabi");
        add(roastedonionitem.get(), "Roasted Onion");
        add(bakedparsnipitem.get(), "Baked Parsnip");
        add(roastedpeanutitem.get(), "Roasted Peanut");
        add(roastedradishitem.get(), "Roasted Radish");
        add(roastedrhubarbitem.get(), "Roasted Rhubarb");
        add(bakedrutabagaitem.get(), "Baked Rutabaga");
        add(roastedscallionitem.get(), "Roasted Scallion");
        add(bakedsweetpotatoitem.get(), "Baked Sweet Potato");
        add(bakedtaroitem.get(), "Baked Taro");
        add(bakedturnipitem.get(), "Baked Turnip");
        add(bakedwaterchestnutitem.get(), "Baked Water Chestnut");
        add(roastedmushroomitem.get(), "Roasted Mushroom");
        add(hotteaitem.get(), "Hot Tea");
        add(hotcoffeeitem.get(), "Hot Coffee");
    }
}
